"""
Management command to add 50 detailed modules to each course
"""
from django.core.management.base import BaseCommand
from courses.models import Course, Module, Lesson
import random


class Command(BaseCommand):
    help = 'Add 50 detailed modules to each course'

    def handle(self, *args, **kwargs):
        self.stdout.write('Adding 50 modules to each course...')

        # Comprehensive 50-module templates by category
        module_templates = {
            'programming': self.get_programming_modules(),
            'data_science': self.get_data_science_modules(),
            'cloud': self.get_cloud_modules(),
            'game': self.get_game_modules(),
            'creative': self.get_creative_modules(),
            'finance': self.get_finance_modules(),
            'health': self.get_health_modules(),
            'lifestyle': self.get_lifestyle_modules(),
            'design': self.get_design_modules(),
            'marketing': self.get_marketing_modules(),
            'language': self.get_language_modules(),
            'business': self.get_business_modules(),
        }

        courses = Course.objects.all()
        updated_count = 0
        total_modules = 0

        for course in courses:
            # Determine category
            category = self.determine_category(course)

            # Get module template
            modules_data = module_templates.get(category, module_templates['business'])

            # Delete existing modules
            course.modules.all().delete()

            # Create 50 modules
            for idx, module_data in enumerate(modules_data[:50]):
                module = Module.objects.create(
                    course=course,
                    title=module_data['title'],
                    description=module_data.get('description', f"{module_data['title']} 학습 내용"),
                    order=idx
                )
                total_modules += 1

                # Add 3-5 lessons per module
                num_lessons = random.randint(3, 5)
                lesson_titles = module_data.get('lessons', [
                    f'{module_data["title"]} 개념',
                    f'{module_data["title"]} 실습',
                    f'{module_data["title"]} 응용',
                    f'{module_data["title"]} 프로젝트'
                ])

                for les_idx, lesson_title in enumerate(lesson_titles[:num_lessons]):
                    lesson_types = ['video', 'video', 'video', 'text', 'quiz']
                    lesson_type = random.choice(lesson_types)

                    Lesson.objects.create(
                        module=module,
                        title=lesson_title,
                        lesson_type=lesson_type,
                        content=f'{lesson_title}에 대한 상세한 학습 내용입니다.',
                        order=les_idx,
                        is_preview=(idx == 0 and les_idx == 0),
                        video_duration=random.randint(600, 3600) if lesson_type == 'video' else 0
                    )

            updated_count += 1
            self.stdout.write(f'  ✅ [{updated_count}/{courses.count()}] {course.title}')

        self.stdout.write(
            self.style.SUCCESS(
                f'\n✅ Updated {updated_count} courses with 50 modules each!'
                f'\n📦 Total modules created: {total_modules}'
                f'\n📚 Average: {total_modules/updated_count:.0f} modules per course'
            )
        )

    def determine_category(self, course):
        """Determine course category from slug or category field"""
        slug = course.slug.lower()
        category = course.category.lower() if course.category else ''

        if any(k in slug for k in ['python', 'java', 'javascript', 'rust', 'kotlin', 'swift', 'programming', 'code']):
            return 'programming'
        elif any(k in slug for k in ['data', 'ml', 'ai', 'analytics', 'science']):
            return 'data_science'
        elif any(k in slug for k in ['aws', 'cloud', 'azure', 'gcp', 'devops', 'kubernetes', 'docker']):
            return 'cloud'
        elif any(k in slug for k in ['game', 'unity', 'unreal', 'godot']):
            return 'game'
        elif any(k in slug for k in ['music', 'video', 'photo', 'drawing', 'art']):
            return 'creative'
        elif any(k in slug for k in ['stock', 'invest', 'trading', 'finance', 'crypto']):
            return 'finance'
        elif any(k in slug for k in ['yoga', 'fitness', 'health', 'workout', 'pilates']):
            return 'health'
        elif any(k in slug for k in ['cooking', 'baking', 'travel', 'garden', 'lifestyle']):
            return 'lifestyle'
        elif any(k in slug for k in ['design', 'ui', 'ux', 'figma', 'photoshop']):
            return 'design'
        elif any(k in slug for k in ['marketing', 'seo', 'ads', 'social']):
            return 'marketing'
        elif any(k in slug for k in ['english', 'language', 'toeic', 'toefl', 'ielts']):
            return 'language'
        else:
            return 'business'

    def get_programming_modules(self):
        return [
            {'title': '개발 환경 설정 및 준비'},
            {'title': '프로그래밍 기초 개념'},
            {'title': '변수와 데이터 타입'},
            {'title': '연산자와 표현식'},
            {'title': '조건문 - if/else'},
            {'title': '반복문 - for/while'},
            {'title': '함수 정의와 호출'},
            {'title': '매개변수와 반환값'},
            {'title': '람다와 익명 함수'},
            {'title': '리스트와 배열'},
            {'title': '딕셔너리와 맵'},
            {'title': '세트와 튜플'},
            {'title': '문자열 처리'},
            {'title': '파일 입출력'},
            {'title': '예외 처리'},
            {'title': '모듈과 패키지'},
            {'title': '객체지향 프로그래밍 개념'},
            {'title': '클래스와 객체'},
            {'title': '상속과 다형성'},
            {'title': '캡슐화와 추상화'},
            {'title': '인터페이스와 추상 클래스'},
            {'title': '디자인 패턴 - Singleton'},
            {'title': '디자인 패턴 - Factory'},
            {'title': '디자인 패턴 - Observer'},
            {'title': '디자인 패턴 - Strategy'},
            {'title': '자료구조 - 스택과 큐'},
            {'title': '자료구조 - 연결 리스트'},
            {'title': '자료구조 - 트리'},
            {'title': '자료구조 - 그래프'},
            {'title': '알고리즘 - 정렬'},
            {'title': '알고리즘 - 검색'},
            {'title': '알고리즘 - 재귀'},
            {'title': '알고리즘 - 동적 프로그래밍'},
            {'title': '테스트 주도 개발 (TDD)'},
            {'title': '유닛 테스트 작성'},
            {'title': '통합 테스트'},
            {'title': '디버깅 기법'},
            {'title': '로깅과 모니터링'},
            {'title': '성능 최적화'},
            {'title': '메모리 관리'},
            {'title': '동시성과 병렬 처리'},
            {'title': '비동기 프로그래밍'},
            {'title': '네트워크 프로그래밍'},
            {'title': 'API 개발'},
            {'title': '데이터베이스 연동'},
            {'title': '보안 best practices'},
            {'title': 'Git 버전 관리'},
            {'title': 'CI/CD 파이프라인'},
            {'title': '배포 전략'},
            {'title': '최종 프로젝트 및 포트폴리오'},
        ]

    def get_data_science_modules(self):
        return [
            {'title': '데이터 사이언스 소개'},
            {'title': 'Python 환경 설정'},
            {'title': 'NumPy 기초'},
            {'title': 'Pandas 데이터프레임'},
            {'title': '데이터 불러오기 (CSV, Excel, DB)'},
            {'title': '데이터 탐색 (EDA)'},
            {'title': '데이터 정제'},
            {'title': '결측치 처리'},
            {'title': '이상치 탐지'},
            {'title': '데이터 변환'},
            {'title': '데이터 시각화 - Matplotlib'},
            {'title': '데이터 시각화 - Seaborn'},
            {'title': '기술 통계'},
            {'title': '확률과 확률분포'},
            {'title': '가설 검정'},
            {'title': '상관 분석'},
            {'title': '회귀 분석'},
            {'title': '머신러닝 개념'},
            {'title': 'Scikit-learn 소개'},
            {'title': '지도 학습 - 선형 회귀'},
            {'title': '지도 학습 - 로지스틱 회귀'},
            {'title': '지도 학습 - 의사결정 나무'},
            {'title': '지도 학습 - 랜덤 포레스트'},
            {'title': '지도 학습 - SVM'},
            {'title': '지도 학습 - KNN'},
            {'title': '비지도 학습 - K-means'},
            {'title': '비지도 학습 - 계층적 군집화'},
            {'title': '비지도 학습 - PCA'},
            {'title': '특성 공학 (Feature Engineering)'},
            {'title': '교차 검증'},
            {'title': '하이퍼파라미터 튜닝'},
            {'title': '모델 평가 지표'},
            {'title': '과적합과 정규화'},
            {'title': '앙상블 기법'},
            {'title': 'XGBoost'},
            {'title': 'LightGBM'},
            {'title': '딥러닝 기초'},
            {'title': 'TensorFlow/Keras 소개'},
            {'title': '신경망 구조'},
            {'title': '역전파 알고리즘'},
            {'title': 'CNN - 합성곱 신경망'},
            {'title': 'RNN - 순환 신경망'},
            {'title': 'LSTM과 GRU'},
            {'title': 'Transformer 아키텍처'},
            {'title': '자연어 처리 (NLP)'},
            {'title': '컴퓨터 비전 (CV)'},
            {'title': '모델 해석과 설명'},
            {'title': '모델 배포 (FastAPI)'},
            {'title': 'MLOps 기초'},
            {'title': '캐글 경진대회 실전'},
        ]

    def get_cloud_modules(self):
        return [
            {'title': '클라우드 컴퓨팅 개념'},
            {'title': 'IaaS, PaaS, SaaS 이해'},
            {'title': '클라우드 프로바이더 비교'},
            {'title': '계정 생성 및 설정'},
            {'title': 'IAM 권한 관리'},
            {'title': '가상 머신 (VM) 생성'},
            {'title': '네트워크 구성 - VPC'},
            {'title': '서브넷과 라우팅'},
            {'title': '보안 그룹과 방화벽'},
            {'title': '로드 밸런서'},
            {'title': '오토 스케일링'},
            {'title': '스토리지 서비스 - 블록'},
            {'title': '스토리지 서비스 - 객체'},
            {'title': '데이터베이스 서비스 - RDS'},
            {'title': '데이터베이스 서비스 - NoSQL'},
            {'title': '컨테이너 기초 - Docker'},
            {'title': '컨테이너 오케스트레이션 - Kubernetes'},
            {'title': '관리형 Kubernetes 서비스'},
            {'title': '서버리스 컴퓨팅 - 함수'},
            {'title': 'API Gateway'},
            {'title': '메시지 큐'},
            {'title': '캐싱 서비스'},
            {'title': 'CDN 설정'},
            {'title': '모니터링과 로깅'},
            {'title': '알람 설정'},
            {'title': '백업과 복구'},
            {'title': '재해 복구 (DR)'},
            {'title': 'Infrastructure as Code'},
            {'title': 'Terraform 기초'},
            {'title': 'Terraform 모듈 설계'},
            {'title': 'CloudFormation/ARM'},
            {'title': 'CI/CD 파이프라인 구축'},
            {'title': 'Jenkins 설정'},
            {'title': 'GitLab CI/CD'},
            {'title': 'GitHub Actions'},
            {'title': '블루-그린 배포'},
            {'title': '카나리 배포'},
            {'title': '컨테이너 보안'},
            {'title': '네트워크 보안'},
            {'title': '암호화와 키 관리'},
            {'title': '컴플라이언스'},
            {'title': '비용 최적화 전략'},
            {'title': '리소스 태깅'},
            {'title': '예산 알람'},
            {'title': '멀티 클라우드 전략'},
            {'title': '하이브리드 클라우드'},
            {'title': '마이그레이션 전략'},
            {'title': '성능 튜닝'},
            {'title': '트러블슈팅'},
            {'title': '실전 아키텍처 설계'},
        ]

    def get_game_modules(self):
        return [
            {'title': '게임 개발 소개'},
            {'title': '게임 엔진 설치'},
            {'title': '인터페이스 둘러보기'},
            {'title': '프로젝트 생성'},
            {'title': '2D vs 3D 게임'},
            {'title': '게임 오브젝트'},
            {'title': '트랜스폼 조작'},
            {'title': '스프라이트와 텍스처'},
            {'title': '애니메이션 시스템'},
            {'title': '물리 엔진 - Rigidbody'},
            {'title': '충돌 감지 - Collider'},
            {'title': '스크립팅 기초'},
            {'title': '게임 로직 구현'},
            {'title': '플레이어 컨트롤러'},
            {'title': '카메라 제어'},
            {'title': '입력 시스템'},
            {'title': 'UI 시스템'},
            {'title': '인벤토리 시스템'},
            {'title': '체력/스코어 시스템'},
            {'title': '게임 상태 관리'},
            {'title': '씬 전환'},
            {'title': '오디오 시스템'},
            {'title': '사운드 이펙트'},
            {'title': '배경 음악'},
            {'title': '파티클 시스템'},
            {'title': '라이팅'},
            {'title': '포스트 프로세싱'},
            {'title': 'AI - 기초'},
            {'title': 'AI - 경로 찾기'},
            {'title': 'AI - 행동 트리'},
            {'title': '멀티플레이어 개념'},
            {'title': '네트워크 동기화'},
            {'title': '서버-클라이언트 구조'},
            {'title': '레벨 디자인'},
            {'title': '게임 밸런싱'},
            {'title': '난이도 곡선'},
            {'title': '게임 경제 시스템'},
            {'title': '수익화 - IAP'},
            {'title': '수익화 - 광고'},
            {'title': '성능 최적화'},
            {'title': '메모리 관리'},
            {'title': '빌드 설정'},
            {'title': '모바일 최적화'},
            {'title': '플랫폼별 설정'},
            {'title': '앱스토어 제출'},
            {'title': '게임 마케팅'},
            {'title': '커뮤니티 관리'},
            {'title': '업데이트 전략'},
            {'title': '포트폴리오 프로젝트'},
            {'title': '게임 퍼블리싱'},
        ]

    def get_creative_modules(self):
        return [
            {'title': '창작의 기초'},
            {'title': '툴 설치 및 설정'},
            {'title': '인터페이스 이해'},
            {'title': '기본 기능 익히기'},
            {'title': '프로젝트 설정'},
            {'title': '레이어 시스템'},
            {'title': '타임라인 이해'},
            {'title': '기본 편집 기법'},
            {'title': '색상 이론'},
            {'title': '구도와 프레이밍'},
            {'title': '타이포그래피'},
            {'title': '텍스처와 패턴'},
            {'title': '브러시와 도구'},
            {'title': '선택과 마스킹'},
            {'title': '변형과 왜곡'},
            {'title': '필터와 이펙트'},
            {'title': '블렌딩 모드'},
            {'title': '조정 레이어'},
            {'title': '스마트 오브젝트'},
            {'title': '벡터 vs 래스터'},
            {'title': '펜 툴 마스터'},
            {'title': '셰이프 디자인'},
            {'title': '패스 편집'},
            {'title': '그라디언트'},
            {'title': '패턴 만들기'},
            {'title': '캐릭터 디자인'},
            {'title': '배경 디자인'},
            {'title': '일러스트레이션'},
            {'title': '스토리보딩'},
            {'title': '애니메이션 원리'},
            {'title': '키프레임'},
            {'title': '이징과 타이밍'},
            {'title': '카메라 워크'},
            {'title': '조명 기법'},
            {'title': '컬러 그레이딩'},
            {'title': '오디오 믹싱'},
            {'title': '사운드 디자인'},
            {'title': '특수 효과'},
            {'title': '합성 기법'},
            {'title': '로토스코핑'},
            {'title': '모션 그래픽'},
            {'title': '3D 통합'},
            {'title': '렌더링 설정'},
            {'title': '출력 포맷'},
            {'title': '작품 정리'},
            {'title': '포트폴리오 구성'},
            {'title': '온라인 발표'},
            {'title': '클라이언트 소통'},
            {'title': '프리랜서로 일하기'},
            {'title': '최종 프로젝트'},
        ]

    def get_finance_modules(self):
        return [
            {'title': '금융 시장 개요'},
            {'title': '투자 기초 개념'},
            {'title': '리스크와 수익'},
            {'title': '자산 배분'},
            {'title': '포트폴리오 이론'},
            {'title': '주식 시장 이해'},
            {'title': '주식 종류'},
            {'title': '거래소와 시장'},
            {'title': '주문 방법'},
            {'title': '기본적 분석 - 재무제표'},
            {'title': '기본적 분석 - 비율 분석'},
            {'title': '기본적 분석 - 가치 평가'},
            {'title': '기술적 분석 - 차트 읽기'},
            {'title': '기술적 분석 - 지표'},
            {'title': '기술적 분석 - 패턴'},
            {'title': '캔들스틱 분석'},
            {'title': '이동평균선'},
            {'title': 'RSI와 MACD'},
            {'title': '볼린저 밴드'},
            {'title': '거래량 분석'},
            {'title': '지지와 저항'},
            {'title': '추세선 그리기'},
            {'title': '매매 전략 - 장기 투자'},
            {'title': '매매 전략 - 단기 트레이딩'},
            {'title': '매매 전략 - 스윙 트레이딩'},
            {'title': '매매 전략 - 데이 트레이딩'},
            {'title': '리스크 관리'},
            {'title': '손절과 익절'},
            {'title': '포지션 사이징'},
            {'title': '분산 투자'},
            {'title': '심리적 함정'},
            {'title': '감정 관리'},
            {'title': '거래 일지'},
            {'title': '백테스팅'},
            {'title': '종목 발굴'},
            {'title': '섹터 분석'},
            {'title': '경제 지표 이해'},
            {'title': '뉴스와 이벤트'},
            {'title': '배당 투자'},
            {'title': '세금 전략'},
            {'title': '계좌 유형'},
            {'title': '수수료 최적화'},
            {'title': '알고리즘 트레이딩 소개'},
            {'title': 'API 활용'},
            {'title': '자동 매매 시스템'},
            {'title': '실전 포트폴리오 구축'},
            {'title': '성과 측정'},
            {'title': '지속적인 학습'},
            {'title': '투자 철학 정립'},
            {'title': '최종 프로젝트'},
        ]

    def get_health_modules(self):
        return [
            {'title': '건강의 중요성'},
            {'title': '운동의 과학'},
            {'title': '신체 구조 이해'},
            {'title': '근육과 골격'},
            {'title': '올바른 자세'},
            {'title': '워밍업의 중요성'},
            {'title': '스트레칭 기법'},
            {'title': '유산소 운동 기초'},
            {'title': '무산소 운동 기초'},
            {'title': '근력 운동 - 가슴'},
            {'title': '근력 운동 - 등'},
            {'title': '근력 운동 - 어깨'},
            {'title': '근력 운동 - 팔'},
            {'title': '근력 운동 - 복근'},
            {'title': '근력 운동 - 다리'},
            {'title': '복합 운동 vs 고립 운동'},
            {'title': '운동 강도 설정'},
            {'title': '세트와 반복수'},
            {'title': '휴식 시간'},
            {'title': '주기화 훈련'},
            {'title': '홈 트레이닝'},
            {'title': '헬스장 기구 사용법'},
            {'title': '프리웨이트 vs 머신'},
            {'title': '기능적 운동'},
            {'title': '코어 강화'},
            {'title': '균형과 안정성'},
            {'title': '유연성 향상'},
            {'title': '부상 예방'},
            {'title': '통증 관리'},
            {'title': '재활 운동'},
            {'title': '영양학 기초'},
            {'title': '탄수화물, 단백질, 지방'},
            {'title': '칼로리 계산'},
            {'title': '식단 구성'},
            {'title': '보충제 가이드'},
            {'title': '수분 섭취'},
            {'title': '식사 타이밍'},
            {'title': '다이어트 전략'},
            {'title': '벌크업 전략'},
            {'title': '체중 유지'},
            {'title': '회복과 휴식'},
            {'title': '수면의 중요성'},
            {'title': '스트레스 관리'},
            {'title': '마음챙김'},
            {'title': '목표 설정'},
            {'title': '진행 상황 추적'},
            {'title': '동기 부여'},
            {'title': '습관 형성'},
            {'title': '평생 건강 계획'},
            {'title': '최종 프로그램'},
        ]

    def get_lifestyle_modules(self):
        return [
            {'title': '시작하기'},
            {'title': '필요한 도구'},
            {'title': '재료 준비'},
            {'title': '기본 기술 1'},
            {'title': '기본 기술 2'},
            {'title': '기본 기술 3'},
            {'title': '초급 레시피 1'},
            {'title': '초급 레시피 2'},
            {'title': '초급 레시피 3'},
            {'title': '초급 레시피 4'},
            {'title': '중급 기술 1'},
            {'title': '중급 기술 2'},
            {'title': '중급 레시피 1'},
            {'title': '중급 레시피 2'},
            {'title': '중급 레시피 3'},
            {'title': '고급 기술 1'},
            {'title': '고급 기술 2'},
            {'title': '고급 레시피 1'},
            {'title': '고급 레시피 2'},
            {'title': '특별 기법 1'},
            {'title': '특별 기법 2'},
            {'title': '계절별 메뉴'},
            {'title': '이벤트 요리'},
            {'title': '건강 레시피'},
            {'title': '다이어트 메뉴'},
            {'title': '비건 옵션'},
            {'title': '글루텐 프리'},
            {'title': '재료 대체'},
            {'title': '보관 방법'},
            {'title': '식품 안전'},
            {'title': '주방 정리'},
            {'title': '도구 관리'},
            {'title': '효율적인 준비'},
            {'title': '시간 절약 팁'},
            {'title': '비용 절감'},
            {'title': '플레이팅'},
            {'title': '사진 촬영'},
            {'title': 'SNS 공유'},
            {'title': '블로그 운영'},
            {'title': '수익화 방법'},
            {'title': '온라인 판매'},
            {'title': '케이터링'},
            {'title': '클래스 운영'},
            {'title': '레시피 개발'},
            {'title': '메뉴 기획'},
            {'title': '고객 관리'},
            {'title': '마케팅'},
            {'title': '브랜딩'},
            {'title': '성장 전략'},
            {'title': '최종 프로젝트'},
        ]

    def get_design_modules(self):
        return [
            {'title': '디자인 원칙 - 균형'},
            {'title': '디자인 원칙 - 대비'},
            {'title': '디자인 원칙 - 강조'},
            {'title': '디자인 원칙 - 리듬'},
            {'title': '디자인 원칙 - 통일성'},
            {'title': '색상 이론'},
            {'title': '색상 조화'},
            {'title': '타이포그래피 기초'},
            {'title': '폰트 선택'},
            {'title': '레이아웃 그리드'},
            {'title': '공간 활용'},
            {'title': 'UI 디자인 기초'},
            {'title': 'UX 리서치'},
            {'title': '사용자 페르소나'},
            {'title': '정보 구조 (IA)'},
            {'title': '와이어프레임'},
            {'title': '프로토타입'},
            {'title': '인터랙션 디자인'},
            {'title': '마이크로 인터랙션'},
            {'title': '애니메이션'},
            {'title': '반응형 디자인'},
            {'title': '모바일 우선'},
            {'title': '접근성 (A11y)'},
            {'title': '디자인 시스템'},
            {'title': '컴포넌트 라이브러리'},
            {'title': '스타일 가이드'},
            {'title': '브랜드 아이덴티티'},
            {'title': '로고 디자인'},
            {'title': '아이콘 디자인'},
            {'title': '일러스트레이션'},
            {'title': '이미지 편집'},
            {'title': '목업 제작'},
            {'title': '프레젠테이션'},
            {'title': '피드백 수용'},
            {'title': '반복 개선'},
            {'title': '사용성 테스트'},
            {'title': '분석과 측정'},
            {'title': '트렌드 분석'},
            {'title': '경쟁사 분석'},
            {'title': '포트폴리오 사례 1'},
            {'title': '포트폴리오 사례 2'},
            {'title': '포트폴리오 사례 3'},
            {'title': '포트폴리오 웹사이트'},
            {'title': '케이스 스터디 작성'},
            {'title': '이력서/자기소개서'},
            {'title': '면접 준비'},
            {'title': '프리랜서 시작'},
            {'title': '클라이언트 관리'},
            {'title': '프로젝트 관리'},
            {'title': '최종 작품'},
        ]

    def get_marketing_modules(self):
        return [
            {'title': '마케팅 개론'},
            {'title': '마케팅 믹스 (4P)'},
            {'title': '타겟 시장 분석'},
            {'title': '경쟁사 분석'},
            {'title': '고객 페르소나'},
            {'title': 'SWOT 분석'},
            {'title': '포지셔닝'},
            {'title': 'USP 개발'},
            {'title': '브랜드 전략'},
            {'title': '콘텐츠 마케팅'},
            {'title': '블로그 마케팅'},
            {'title': 'SEO 기초'},
            {'title': '키워드 리서치'},
            {'title': '온페이지 SEO'},
            {'title': '오프페이지 SEO'},
            {'title': '기술적 SEO'},
            {'title': 'SEM - 검색 광고'},
            {'title': '구글 애즈 기초'},
            {'title': '키워드 전략'},
            {'title': '광고 그룹 구성'},
            {'title': '광고 문구 작성'},
            {'title': '입찰 전략'},
            {'title': '품질 평가점수'},
            {'title': 'SNS 마케팅 전략'},
            {'title': '페이스북 마케팅'},
            {'title': '인스타그램 마케팅'},
            {'title': '유튜브 마케팅'},
            {'title': '틱톡 마케팅'},
            {'title': '링크드인 마케팅'},
            {'title': '인플루언서 마케팅'},
            {'title': '이메일 마케팅'},
            {'title': '리스트 구축'},
            {'title': '이메일 자동화'},
            {'title': '퍼널 마케팅'},
            {'title': '랜딩 페이지 최적화'},
            {'title': 'CRO (전환율 최적화)'},
            {'title': 'A/B 테스트'},
            {'title': '멀티베리에이트 테스트'},
            {'title': '리타게팅'},
            {'title': '리마케팅'},
            {'title': '제휴 마케팅'},
            {'title': '바이럴 마케팅'},
            {'title': 'GA4 설정'},
            {'title': '구글 태그 매니저'},
            {'title': '전환 추적'},
            {'title': 'KPI 설정'},
            {'title': '대시보드 구축'},
            {'title': 'ROI 계산'},
            {'title': '마케팅 자동화'},
            {'title': '최종 캠페인 프로젝트'},
        ]

    def get_language_modules(self):
        return [
            {'title': '알파벳과 발음'},
            {'title': '기본 인사'},
            {'title': '자기소개'},
            {'title': '숫자와 날짜'},
            {'title': '시간 표현'},
            {'title': '명사'},
            {'title': '대명사'},
            {'title': '동사 - 현재'},
            {'title': '동사 - 과거'},
            {'title': '동사 - 미래'},
            {'title': '형용사'},
            {'title': '부사'},
            {'title': '전치사'},
            {'title': '접속사'},
            {'title': '의문문'},
            {'title': '부정문'},
            {'title': '일상 어휘 100'},
            {'title': '음식 관련 어휘'},
            {'title': '쇼핑 어휘'},
            {'title': '여행 어휘'},
            {'title': '직장 어휘'},
            {'title': '가족과 관계'},
            {'title': '취미와 여가'},
            {'title': '날씨 표현'},
            {'title': '감정 표현'},
            {'title': '의견 표현'},
            {'title': '전화 통화'},
            {'title': '약속 잡기'},
            {'title': '길 묻기'},
            {'title': '식당에서 주문'},
            {'title': '호텔 체크인'},
            {'title': '공항에서'},
            {'title': '쇼핑하기'},
            {'title': '병원 방문'},
            {'title': '은행 업무'},
            {'title': '문법 - 시제'},
            {'title': '문법 - 조동사'},
            {'title': '문법 - 가정법'},
            {'title': '문법 - 관계사'},
            {'title': '듣기 연습'},
            {'title': '듣기 전략'},
            {'title': '말하기 연습'},
            {'title': '발음 교정'},
            {'title': '읽기 연습'},
            {'title': '독해 전략'},
            {'title': '쓰기 연습'},
            {'title': '에세이 작성'},
            {'title': '시험 대비'},
            {'title': '모의고사'},
            {'title': '최종 평가'},
        ]

    def get_business_modules(self):
        return [
            {'title': '비즈니스 기초'},
            {'title': '경영 개론'},
            {'title': '조직 구조'},
            {'title': '리더십 스타일'},
            {'title': '팀 빌딩'},
            {'title': '커뮤니케이션'},
            {'title': '프레젠테이션'},
            {'title': '협상 기술'},
            {'title': '갈등 해결'},
            {'title': '의사결정'},
            {'title': '문제 해결'},
            {'title': '비판적 사고'},
            {'title': '창의적 사고'},
            {'title': '시간 관리'},
            {'title': '우선순위 설정'},
            {'title': '생산성 도구'},
            {'title': '목표 설정 (SMART)'},
            {'title': 'OKR 프레임워크'},
            {'title': '프로젝트 관리 기초'},
            {'title': '애자일 방법론'},
            {'title': '스크럼'},
            {'title': '칸반'},
            {'title': '일정 관리'},
            {'title': '리스크 관리'},
            {'title': '품질 관리'},
            {'title': '이해관계자 관리'},
            {'title': '재무 기초'},
            {'title': '회계 원리'},
            {'title': '재무제표 읽기'},
            {'title': '손익계산서'},
            {'title': '대차대조표'},
            {'title': '현금흐름표'},
            {'title': '예산 수립'},
            {'title': '비용 관리'},
            {'title': 'ROI 분석'},
            {'title': '마케팅 전략'},
            {'title': '영업 기법'},
            {'title': '고객 관계 관리 (CRM)'},
            {'title': '데이터 분석'},
            {'title': 'Excel 고급'},
            {'title': '대시보드 구축'},
            {'title': '비즈니스 인텔리전스'},
            {'title': '창업 준비'},
            {'title': '사업 계획서'},
            {'title': '투자 유치'},
            {'title': '법률 기초'},
            {'title': '윤리 경영'},
            {'title': '지속 가능 경영'},
            {'title': '케이스 스터디'},
            {'title': '최종 프로젝트'},
        ]
